// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vclpigofteuslydkcxxt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZjbHBpZ29mdGV1c2x5ZGtjeHh0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyNTYxMjYsImV4cCI6MjA2MzgzMjEyNn0.sTfQIW1tCNF6LN_NoAgShDorvBvEK-6_I_ksW4NufJg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);